spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/IdeaProjects/jpashop/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create      # 매 애플리케이션 실행 시 db 초기화
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 #컬렉션을 지연로딩할 때 in 쿼리를 사용한 최적화를 통해 1+N 문제를 해결.
    show-sql: true
#    open-in-view: false  # OSIV : 트랜잭션 종료 시 영속성 컨텍스트 닫고, db connection 반환. 모든 지연로딩을 트랜잭션 안에서 처리해야 하나 커넥션 풀 장애가 발생하지 않음

logging:
  level:
    org.hibernate.sql: trace    #show_sql 은 sout으로 출력하므로 사용 지양. 운영 측면에서 로그로 보관해야 함