spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/IdeaProjects/jpashop/jpashop;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create      # 매 애플리케이션 실행 시 db 초기화
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug    #show_sql 은 sout으로 출력하므로 사용 지양. 운영 측면에서 로그로 보관해야 함